= Dotfiles
Pierre-Luc Perrier <dev@the-pluc.net>
:description: Pluc's dotfiles
:keywords: dotfiles,linux,shell
:nofooter:
:icons: font
:sectanchors:
:hide-uri-scheme:
:linkattrs:
:source-highlighter: prettify
:experimental:

== Dependencies

http://compression.ca/pbzip2/[pbzip2]:: Parallel implementation of the bzip2 block-sorting file compressor
http://www.vergenet.net/~conrad/software/xsel/[xsel]:: XSel is a command-line program for getting and setting the contents of the X selection
https://ccache.samba.org/[ccache]:: Compiler cache that speeds up recompilation by caching previous compilations
https://github.com/BurntSushi/ripgrep[ripgrep]:: A search tool that combines the usability of ag with the raw speed of grep
https://github.com/antifuchs/chars[chars]:: Command line tool to display information about unicode characters.
https://github.com/bootandy/dust[dust]:: du + rust = dust. Like du but more intuitive
https://github.com/bvaisvil/zenith[zenith]:: Terminal system monitor with histograms, written in Rust
https://github.com/dalance/procs[procs]:: A modern replacement for ps written by Rust
https://github.com/darakian/ddh[ddh]:: Manage duplicate files
https://github.com/dbrgn/tealdeer[tealdeer]:: A fast tldr client in Rust.
https://github.com/ggreer/the_silver_searcher[the_silver_searcher]:: Code searching tool similar to Ack, but faster
https://github.com/jwilm/alacritty[alacritty]:: A cross-platform, GPU-accelerated terminal emulator
https://github.com/sharkdp/bat[bat]:: Cat clone with syntax highlighting and git integration
https://github.com/sharkdp/fd[fd]:: Simple, fast and user-friendly alternative to find
https://github.com/sharkdp/hyperfine[hyperfine]:: A command-line benchmarking tool
https://github.com/tmux/tmux/wiki[tmux]:: A terminal multiplexer
https://github.com/watchexec/watchexec[watchexec]:: Executes commands in response to file modifications
https://the.exa.website/[exa]::ls replacement
https://www.gnu.org/software/emacs/emacs.html[emacs]:: The extensible, customizable, self-documenting real-time display editor
https://www.mozilla.org/firefox/[firefox]:: Standalone web browser from mozilla.org
https://www.zlib.net/pigz[pigz]:: Parallel implementation of the gzip file compressor

=== A tester

* sd: sed alternative
* podman
* jq/jc
* dot (rust) dotfile manager

== Key bindings

=== tmux

[cols=">1,1,2m,3"]
|===
|Prefix |Key |Command |Description

|kbd:[C-b] |kbd:[/] |command-promp |Open the tmux internal command prompt

|kbd:[C-b] |kbd:["] |split-window -h |Split window horizontally

|kbd:[C-b] |kbd:[é] |split-window -v |Split window vertically

|kbd:[C-b] |kbd:[a] |last-window |Switch to last window

|kbd:[C-b] |kbd:[l] |choose-tree |List windows as a tree

|kbd:[C-b] |kbd:[L] |find-window |Search window

|kbd:[C-b] |kbd:[K] |kill-window |Kill window

|kbd:[C-b] |kbd:[q] |last-pane |Switch to the previously active pane

|kbd:[C-b] |kbd:[f] |resize-pane -Z |Zoom / unzoom pane

|kbd:[C-b] |kbd:[k] |kill-pane |Kill pane

|kbd:[C-b] |kbd:[Q] |display-panes |Show panes numbers

|kbd:[C-b] |kbd:[:] |copy-mode |Enter copy mode

|kbd:[C-b] |kbd:[!] |paste-buffer|Paste copy buffer into current pane

|kbd:[C-b] |kbd:[R] |source-file |Reload configuration
|===
