#!/usr/bin/env sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xresources=${HOME}/.Xresources
[[ -f "${xresources}" ]] && xrdb -merge "${xresources}"

exec mate-session
