#!/usr/bin/env bash
#
# ~/.bash_aliases
#
# List of aliases, should be sourced by ~/.bashrc.

alias ls='ls --color=auto'
alias la='ls -lah'
alias ll='ls -lAh'
alias https='http --default-scheme=https'
